font_family      Fira Code
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        16.0

background_opacity 0.85
background_blur    15
window_padding_width 10

hide_window_decorations titlebar-only

enable_audio_bell no

# Tab styling
tab_bar_style        powerline
tab_powerline_style  slanted
active_tab_font_style bold

# 1. Set the thickness of the borders (e.g., 2.0pt or 3px)
window_border_width 2.0pt

# 2. Control whether thin lines are drawn around windows even if they are inactive
draw_minimal_borders yes

# 3. Add internal spacing between the text and the window edge
window_padding_width 10

# 4. Define custom Hex colors for active and inactive windows
active_border_color #f403fc
inactive_border_color #44475a

# 5. Define an accent color for a window alerting you with a terminal bell
bell_border_color #ff5555

# Force borders to always show so color properties can apply
draw_window_borders_for_single_window yes

# Remember layout splits
enabled_layouts splits,stack

# Keep current working directory for new windows and tabs
map ctrl+shift+enter new_window_with_cwd
map ctrl+shift+t     new_tab_with_cwd

# BEGIN_KITTY_THEME
# GitHub Dark Dimmed
include current-theme.conf
# END_KITTY_THEME
